name: Notify Delivery CI

on:
  pull_request:
    paths:
      - "notify-service/notify-delivery/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./notify-service/notify-delivery

jobs:
  notify-delivery-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "notify-delivery"
      working_directory: "./notify-service/notify-delivery"
      codecov_flag: "notifydelivery"